db:
  # Endpoint to the database
  endpoint: ""
  # Supported providers: Firebase
  provider: "Firebase"
  firebase_credentials:
    project_id: "<PROJECT_ID>"
    private_key_id: "<PRIVATE_KEY_ID>"
    private_key: "<PRIVATE_KEY>"
    client_email: "<CLIENT_EMAIL>"
    client_id: "<CLIENT_ID>"
    client_x509_cert_url: "<CLIENT_X509_CER>"
github:
  organization: "kiali"
gcp_function: false
