# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy_function:
    name: Deploy Grownity function
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
    - uses: actions/checkout@v2

    - id: auth
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{secrets.GCP_CREDENTIALS}}

    - id: 'deploy'
      uses: 'google-github-actions/deploy-cloud-functions@v0'
      with:
        name: 'GrownityOn'
        runtime: 'go116'
        region: 'europe-west3'
        entry_point: 'GrownityOn'
        env_vars: DB_URL=${{secrets.DB_URL}},FB_PROJECT_ID=${{secrets.FB_PROJECT_ID}},FB_PRIVATE_KEY_ID=${{secrets.FB_PRIVATE_KEY_ID}},FB_PRIVATE_KEY=${{secrets.FB_PRIVATE_KEY}},FB_CLIENT_EMAIL=${{secrets.FB_CLIENT_EMAIL}},FB_CLIENT_ID=${{secrets.FB_CLIENT_ID}},FB_CLIENT_X509_CERT_URL=${{secrets.FB_CLIENT_X509_CERT_URL}}
        build_environment_variables: GOOGLE_BUILDABLE=.


        
