name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    env: 
      FB_SERVICE_ACCOUNT: ${{secrets.TEST_FB_SERVICE_ACCOUNT}}
      DB_URL: ${{secrets.TEST_DB_URL}}
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...  